### ISSUE TITLE
Unable to resolve @nrwl/node:node.

### ISSUE THREAD

**Issue by eugle** [Tony133/nestjs-apps-collection#755]
Unable to resolve @nrwl/node:node.

```
PS D:\learn\nestjs\nestjs-apps-collection> npx nx serve nestjs-graphql-apollo-schema-first

 >  NX   Unable to resolve @nrwl/node:node.

   Cannot find module '@nx/node/src/executors/node/schema.json'
   Require stack:
   - D:\learn\nestjs\nestjs-apps-collection\node_modules\.pnpm\nx@16.5.0\node_modules\nx\src\config\workspaces.js
   - D:\learn\nestjs\nestjs-apps-collection\node_modules\.pnpm\nx@16.5.0\node_modules\nx\src\config\configuration.js
   - D:\learn\nestjs\nestjs-apps-collection\node_modules\.pnpm\nx@16.5.0\node_modules\nx\src\utils\package-manager.js
   - D:\learn\nestjs\nestjs-apps-collection\node_modules\.pnpm\nx@16.5.0\node_modules\nx\bin\init-local.js
   - D:\learn\nestjs\nestjs-apps-collection\node_modules\.pnpm\nx@16.5.0\node_modules\nx\bin\nx.js
   Pass --verbose to see the stacktrace.
```

Can't start, please help me

**Comment by Tony133** [comment]
Hi @eugle ,

Thanks for the report, I updated the nx version to 16.3.2, it should work now. From what I understand, the "serve" command does not work with the 16.5.x version of nx. I will do more verification.


<img width="1170" alt="nx-16 3 x" src="https://github.com/Tony133/nestjs-apps-collection/assets/11542387/5b2b6e16-6428-48ac-b418-5a6fbab94beb">
